### ISSUE TITLE
Connecting to valora app does not make the network as Mainnet

### ISSUE THREAD

**Issue by sihan-tawsik** [celo-org/use-contractkit#106]
When connecting to Valora app, use-contractkit chooses the last network it was connected to instead of Mainnet.
How to reproduce:
1. Connect with celo-extention wallet on Alfajores network with use-contractkit
2. Disconnect from the address
3. Connect with valora app

![image](https://user-images.githubusercontent.com/37876720/154090568-b831bcbe-19c9-4758-96a7-cb57d60a2620.png)

Test Config:
Browser: Google Chrome
OS: EndeavourOS Linux x86_64
Kernel: 5.16.8-arch1-1

Valora app: 1.24.1
Platform: Android

Use-contractkit version: 2.1.4

cc: @Geektrovert, @Pinotio

**Comment by aaronmgdr** [comment]
Hmm for most wallets It makes sense to keep last network, but since Valora only supports celo mainnet switching network when Valora is used is probably a good idea. 

unless there is someway to use other networks with valora im not aware of @jeanregisser

**Comment by aaronmgdr** [comment]
Rather than force switching the network im thinking it might be better if we ask or prompt users to switch. And come up with a solution that works for other wallets like Celo dance that only support celo.
