### ISSUE TITLE
Automatically switch to valora when approving payment

### ISSUE THREAD

**Issue by sihan-tawsik** [celo-org/use-contractkit#108]
Is it possible to make use-contractkit open valor app when a payment method is called from a mobile browser?
To elaborate it:
Let's say, I used a mobile browser to visit my site which uses use-contractkit. I connect to Valora and from the website, I invoke the transfer. Right now, we have to manually switch to Valora and approve the payment. Is it realistic that invoking the transfer automatically switches over to Valora?

**Comment by aaronmgdr** [comment]
We are looking into this.

**Comment by sihan-tawsik** [comment]
Thank you for the fast response and implementation 💯
