### ISSUE TITLE
Unable submit/sign transaction with Valora on iOS

### ISSUE THREAD

**Issue by fodisi** [celo-org/use-contractkit#114]
Hello, GoodGhosting team here.
Opening new issue as suggested on https://github.com/celo-org/use-contractkit/issues/89#issuecomment-1047094763.

We're unable to sign transactions using valora on iOS. Using iOS 15.1 on iPhone 7 Plus (model NN5X2LL/A).
It does worked on an iPhone 7 device (not Plus) with iOS version 14.4

use-contractkit version: `"@celo-tools/use-contractkit": "3.0.0-beta2"`

contractkit version: `"@celo/contractkit": "^1.5.2"`

Valora version and platform (iOS and/or Android): version `1.25.2` on iOS

Network used (mainnet or alfajores):`mainnet`

Steps to reproduce (ideally with a link to a website where the problem can be reproduced)
On https://use-contractkit-gamma.vercel.app/
1. Connect wallet on Mainnet using Valora (this step works)
2. Submit transaction (test `sendTransaction`) and manually go to Valora app to approve the transaction. It gets stuck in this step and Valora never shows the in-app pop up to approve the transaction. User gets stuck here.

Whether the problem can be reproduced on https://use-contractkit-gamma.vercel.app/
`Yes`

Any logs you have
n/a

We're facing the same issue on our internal staging url of goodghosting (where we're testing valora integration). I didn't post the url here since it can be reproduced on https://use-contractkit-gamma.vercel.app/, but let me know if needed.

PS: I'm updating my iOS to 15.3.1 to check if the issue goes away. I'll update this ticket later once the update is completed.

Thank you

**Comment by fodisi** [comment]
Update: updated my device to iOS 15.3.1 (current latest version) and still having the same issue.
Thank you

**Comment by jeanregisser** [comment]
Thanks, I'm looking at this.
I see the same problem as you with https://use-contractkit-gamma.vercel.app/

**Comment by aaronmgdr** [comment]
hmm when I do this with my iphone with valora it works for me both when connecting to desktop site and thru mobile browser.

**Comment by dckesler** [comment]
I think this is probably fixed with version 3.0.1. Feel free to re-open if not.
