### ISSUE TITLE
Figure out way to know which wallets support setting feeCurrency

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/use-contractkit#117]
Wallets designed for Celo like valora, CeloWallet,  offer the capability to add an additional field to tx for feeCurrency. wallets which support only ethereum style tx like metamask do not. 

Right now use-ck offers functions to change fee currency regardless of wallet. we should be more discerning.

**Comment by aaronmgdr** [comment]
Hearing that when using wallet connect v1 the fee currency is param is not sent to wallet anyway.

**Comment by nicolasbrugneaux** [comment]
This was fixed by #168
