### ISSUE TITLE
Open Dapp in MetaMask Mobile

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/use-contractkit#162]
As a Degen 
When I am on a Mobile Phone Browser
When I choose open in MetaMask Mobile
I expect the dapp I am in to open in metamask mobile's  in app browser. 

This can be done be appending the current browser location to 

`https://metamask.app.link/dapp/` like `https://metamask.app.link/dapp/app.ubeswap.org`

see https://docs.metamask.io/guide/mobile-best-practices.html#deeplinking

**Comment by aaronmgdr** [comment]
make sure this only happens when on mobile

**Comment by zhaonancy** [comment]
https://github.com/celo-org/use-contractkit/issues/170
