### ISSUE TITLE
Cancelling a connection request from the wallet should directly close QR code and show feedback

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/use-contractkit#165]
### Current behavior

After cancelling a WalletConnect connection request from the wallet, the QR code modal is still visible in the dapp but can't be used anymore to re-connect.

See an example of this in the video.

https://user-images.githubusercontent.com/57791/166924541-0e122283-11dd-4f61-a583-f60248df8412.MP4

### Desired behavior

If the user decides to cancel the connection request from the wallet,
the QR code modal should close and show a warning/error that the connection was cancelled

### Steps to Reproduce

1. On your mobile, navigate to https://use-contractkit-gamma.vercel.app/
2. Tap "Connect"
3. Select Valora
4. Once Valora launches and promot to Allow/Cancel, choose Cancel
5. Bring the browser back to the front
6. Notice the QR code modal is still display, but can't be used anymore to connect. Tapping "Open Valora" opens Valora but the connection times out (since the session was denied previously).

This can be reproduced similarly across Desktop and Mobile.

### Versions

- Valora 1.31.0 on iOS 15.4.1
- use-contractkit that was deployed on https://use-contractkit-gamma.vercel.app/ on 2022-05-05.

**Comment by dckesler** [comment]
I think this is the same sort of thing we want to address with #144
