### ISSUE TITLE
Provide a way to see the version of use-contractkit used by a dapp

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/use-contractkit#167]
### What would you like?

I would love to have a way to see the version of `use-contractkit` used by a dapp.

It could be added at the bottom of the connection modal after tapping "Show More".

<img width="457" alt="Screenshot 2022-05-05 at 15 41 52" src="https://user-images.githubusercontent.com/57791/166936353-3f8c6900-537e-40c5-94ac-3c9e97dc3ccb.png">

### Why is this needed?

This is important to debug connection issues on dapps.

**Comment by aaronmgdr** [comment]
I was just thinking the same thing

**Comment by nicolasbrugneaux** [comment]
Here's an attempt at it (without being too intrusive) on the new designs, wdyt?

![Screenshot 2022-05-05 at 17 48 03](https://user-images.githubusercontent.com/3650621/166962190-19364826-2398-41b5-97cf-911af165fd8f.png)
![Screenshot 2022-05-05 at 17 48 00](https://user-images.githubusercontent.com/3650621/166962199-9d5d8498-cdfa-454f-b19b-c8c418bcc9b5.png)
