### ISSUE TITLE
Example app: dark-mode toggle is interfering with the modal

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/use-contractkit#183]
On Mobile The toggle darkmode and "Choose a Wallet" texts are on top of each other

Also I can scroll down to see more wallets

And it seems to be missing the search functionality.

**Comment by nicolasbrugneaux** [comment]
On yeah the toggle wasnt supposed to go through it was a helper for me to debug the theme locally. I'll try to make it a real thing on the example app then
