### ISSUE TITLE
Error from One wallet not cleaned up when switching to other wallet

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/use-contractkit#211]
If any error happens while using ledger connector, after disconnecting that error shows up when the modal is re opened for other wallets. 

It should be cleared on disconnect

![Screen Shot 2022-05-23 at 11 26 31 AM](https://user-images.githubusercontent.com/3814795/169883995-9e021f3f-bbe9-403e-902e-59a94b207f6d.png)

**Comment by gickyDEV** [comment]
Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.

**Comment by gickyDEV** [comment]
Talk to Ledgerwallet Support on the [Live support chat](ledger-community.com) so that your issue can be looked into.
