### ISSUE TITLE
Sending multiple transactions doesn't work with Valora on Android

### ISSUE THREAD

**Issue by calianlucian** [celo-org/use-contractkit#44]
Using Chrome on Android, when sending multiple transactions to Valora, only the first transaction is executed. The code looks something like these:

const actions = [getTxAction(txParams[0]), getTxAction(txParams[1])]

try {
await performActions(...actions)
} catch(error) {
....
}

This works well on iOS, both actions are executed through Valora, but on Android only the first action is executed and the popup remains hanging. I think the problem is related to the fact that when Valora redirects back to the app, it doesn't redirect to the same tab, but it opens a new tab in the group tab. This way, it seems that the internal state is not updated and it doesn't continue to the next action in the array.

**Comment by aslawson** [comment]
@calianlucian Valora has temporarily disabled walletconnectv2, we will be working to add v1 support Valora will be usable in use-contractkit again. sorry for the inconvenience, we expect another 2 weeks for a fix.

**Comment by dckesler** [comment]
Closing this for now with the release of v2. If this is still an issue feel free to re-open.
