### ISSUE TITLE
Instabilities with WalletConnect v2, consider supporting v1 instead

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/use-contractkit#53]
There has been a couple of issues with WalletConnect v2 over the past few months.

Latest in date: https://github.com/WalletConnect/walletconnect-monorepo/issues/625

As a result, `use-contractkit` has been providing a broken WalletConnect experience to DApps and Wallets using it for some time.

Because of these instabilities, for [Valora](https://github.com/valora-inc/wallet) we've decided to disable WalletConnect v2 support until it is considered stable.

At this point I think it would be good to add support for WalletConnect v1 instead in `use-contractkit`.

Of course my perspective is biased toward Valora and its users, but it seems given all issues we've seen now with v2, we should do what's best for our users.

What do you think?

**Comment by tunjayhuseynov** [comment]
If it works it is ok, better than the current situation

**Comment by jeanregisser** [comment]
Yes

**Comment by dckesler** [comment]
We added walletconnect v1 support with use-contractkit v2.
