### ISSUE TITLE
Wallet Address Invalid

### ISSUE THREAD

**Issue by tunjayhuseynov** [celo-org/use-contractkit#57]
When I scan QR in Valora, I get Wallet Address Invalid error, also Metamask closes itself and reopen again

**Comment by dckesler** [comment]
Valora has moved to only support V1 of WalletConnect whereas use-contractkit only has v2 support. We're currently working on adding V1 support in use-contractkit.

**Comment by dckesler** [comment]
use-contractkit v2 is out and it supports WalletConnect v1 so it should work with Valora now.
