### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by camolezi** [celo-org/use-contractkit#85]
Hello everyone,

We're having a problem running the package. After the installation we're getting the same error as in the issue https://github.com/celo-org/use-contractkit/issues/45

We used the workaround described in the issue, and that fixed the problem. But now we're getting the following error:

![image](https://user-images.githubusercontent.com/28444499/146815199-ca61afae-d8dc-43d8-b922-e0dc35c948c4.png)

Any help solving this issue is appreciated, thanks.

**Comment by jmrossy** [comment]
@dckesler is working on a fix and is hopeful to release a v2.1.1 soon

**Comment by dckesler** [comment]
Yes it is an issue with mismatched WalletConnect dependencies inside of WalletConnect's types. We are aware of the issue and have seemingly found a way around it. Should release soon.

**Comment by camolezi** [comment]
Thanks!, are there any workarounds that we can use in the meantime?

**Comment by ashutoshvarma** [comment]
@dckesler is this fixed in v2.1.2?

**Comment by nicolasbrugneaux** [comment]
It should be fixed as of 2.1.2 released on the 30th of December. Closing this issue. Feel free to reopen if the issue happens again
