### ISSUE TITLE
Error approving payments with Valora

### ISSUE THREAD

**Issue by Pinotio** [celo-org/use-contractkit#89]
Celo.Tax team here.

Using version 2.0.1, it is possible to connect with Valora but not approve payments. When moving to payment approval, Valora gets as far as asking for a pin. After the pin is entered, nothing further happens.

(Same issue using Brave and Safari as browsers, and connecting Valora via QR code or directly.)

**Comment by jmrossy** [comment]
@dckesler Note, I believe this is the same error I've been seeing.
https://github.com/valora-inc/wallet/issues/1559

**Comment by Bridgerz** [comment]
Experiencing similar. Only seems affected if on iOS only and not using native browser for dApp.

**Comment by fodisi** [comment]
GoodGhosting team here.
Same issue. User is able to connect, but when it's time to sign the submitted transaction on Valora wallet, there's just a infinite "loading animation" until the tx times out.

Issue happening with multiple v2.x and also v3x versions of us-contractkit.

**Comment by jeanregisser** [comment]
The original issue the Celo.Tax team was having has been resolved.

Long story short, you need to be on Valora >= 1.25 and `use-contractkit` >= 3.0.0-beta.

I'm gonna close this issue and encourage each of you to open a new one with more details about the specific issue you're having, including the following info:
1. `use-contractkit` version
2. Valora version
3. Steps to reproduce (ideally with a link to a website where the problem can be reproduced)
4. Whether the problem can be reproduced on https://use-contractkit-gamma.vercel.app/
5. Any logs you have

Thank you 🙏
