### ISSUE TITLE
Unable to read property of undefined

### ISSUE THREAD

**Issue by sihan-tawsik** [celo-org/use-contractkit#90]
Hi,
I am using use-contractkit version 2.0.1 to connect users to wallet. But I'm facing this visual issue here on the modal which says:
`Unable to read property of undefined (reading 'replace')`
Here are the screenshots:
![Screenshot_2022-01-07_21-27-09](https://user-images.githubusercontent.com/37876720/148566607-181ec5e5-01d6-466d-b6d5-3226f226ec73.png)

![Screenshot_2022-01-07_21-29-16](https://user-images.githubusercontent.com/37876720/148566568-a6bc6519-44e4-4718-a8e1-3e4484d0c8ab.png)

Is there a way to remove this text from the modal?

**Comment by tunjayhuseynov** [comment]
@sihan-tawsik Did you solve it? I am facing it too. It happens when I refresh the page. Cannot reconnect to the last connection

**Comment by sihan-tawsik** [comment]
> @sihan-tawsik Did you solve it? I am facing it too. It happens when I refresh the page. Cannot reconnect to the last connection

No, I haven't solved the issue from my end still

**Comment by musayann** [comment]
Having the same issue on version `2.1.2` happens as well on page refresh

**Comment by nicolasbrugneaux** [comment]
Hi everyone and thanks for commenting on the issue! I'm currently struggling to reproduce the bug locally, is there any chance you have an example app running and having the issue that I could debug?

**Comment by musayann** [comment]
> Hi everyone and thanks for commenting on the issue! I'm currently struggling to reproduce the bug locally, is there any chance you have an example app running and having the issue that I could debug?

You can clone this app https://github.com/dacadeorg/celo-nft-minter/tree/ft/update-celo-depency on the `update-celo-depency` branch. Once you install the dependencies and run the project you should see a connect wallet button which works normally. After connecting your wallet refresh the page and you should see the error in the console log

**Comment by tunjayhuseynov** [comment]
I solved my problem by upgrading version to 3.0.0-beta

**Comment by aaronmgdr** [comment]
Hi all

Ive been able to reproduce using the repo @musayann created. 

It seems to be happening that feeCurrency is undefined because when initializing on refresh it fetches the arguments from local storage but feeCurrency is not getting saved there. still figuring out why. 

Options im considering are  if feeCurrency is undefined to simply abort calling update or to pass in GoldTokenContract.

**Comment by dckesler** [comment]
I think I've found the problem. Fixing it today hopefully we can release 3.0.0 out of beta today or tomorrow with the fix.
